/* ============================================================
   Data Romo Jesuit Indonesia (PROVINDO)
   Sumber: https://jesuits.id (Berita Pengutusan, Obituari, Komunitas)
   Dikompilasi per September 2026. Bukan daftar resmi.
   Catatan: Provinsi Indonesia memiliki ±339 Jesuit (246 imam,
   74 skolastik, 19 bruder; data 2021). Daftar lengkap per nama
   tidak dipublikasikan (hanya Catalogus internal), sehingga
   direktori ini belum lengkap.
   ============================================================ */

/* ---------- MASIH AKTIF BERTUGAS (dari Berita Pengutusan) ---------- */
const activeJesuits = [
  { name: "P. Thomas Hidya Tjaya", role: "Wakil Pater Unit Skolastikat Kampung Ambon, Kolese Hermanum", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Ferdinandus Effendi Kusuma Sunur", role: "Pater Unit Skolastikat Kampung Ambon, Kolese Hermanum", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Thomas Aquinas Maswan Susinto", role: "Pater Unit Skolastikat Johar Baru, Kolese Hermanum", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Josephus Ageng Marwata", role: "Wakil Pater Unit Skolastikat Johar Baru, Kolese Hermanum", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Vincentius Doni Erlangga Satriawan", role: "Koordinator Tim Promosi Panggilan", place: "Indonesia", since: "1 Sep 2026", ordination: "Imam 31 Jul 2024, Gereja St. Antonius Padua, Yogyakarta", diakon: "Diakon 25 Jan 2024, Kapel Seminari Tinggi St. Paulus, Kentungan" },
  { name: "P. Benedictus Bambang Triatmoko", role: "Kolese Kanisius", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Paulus Agung Wijayanto", role: "Pastor Kepala Gereja Paroki Internasional St. Petrus Canisius", place: "Jakarta", since: "1 Sep 2026" },
  { name: "P. Heribertus Heri Setyawan", role: "Studi khusus magister ilmu sejarah, SOAS - University of London", place: "London", since: "15 Sep 2026", kaulAkhir: "Kaul akhir 2023, Kapel St. Robertus Bellarminus, Mrican, Yogyakarta (19 Mar 2024)" },
  { name: "P. Joannes de Britto Dwijo Atmoko", role: "Staf Rumah Retret Kristus Raja", place: "Girisonta", since: "15 Jul 2026" },
  { name: "P. Odemus Bei Witono", role: "Wisma Johar Baru, Kolese Hermanum", place: "Jakarta", since: "15 Jul 2026" },
  { name: "P. Ernest Justin", role: "Studi magister psikologi terapan, Universitas Fordham", place: "New York", since: "1 Agt 2026", kaulAkhir: "Kaul akhir 2023, Kapel St. Robertus Bellarminus, Mrican, Yogyakarta (19 Mar 2024)" },
  { name: "P. Romanus Wahana Wegig", role: "Vikaris Parokial Paroki Santo Yusup", place: "Baturetno", since: "15 Jul 2026" },
  { name: "P. Martinus Dam Febrianto", role: "Direktur JRS Indonesia", place: "Indonesia", since: "1 Agt 2026", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 10 Mei 2021, Gereja St. Antonius Padua, Kotabaru" },
  { name: "P. Rafael Mathando Hinganaday", role: "Yadapen dan Paroki Santo Yusup", place: "Gedangan", since: "1 Agt 2026", ordination: "Imam 31 Jul 2019, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Filipus Frederick Ray Popo", role: "Studi khusus filsafat, Brown University", place: "Rhode Island", since: "1 Agt 2026", ordination: "Imam 29 Jul 2026, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 26 Jan 2026" },
  { name: "P. Philipus Bagus Widyawan", role: "Pastor Kepala Paroki Santo Yohanes Pemandi", place: "Waghete", since: "15 Agt 2026", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 10 Mei 2021, Gereja St. Antonius Padua, Kotabaru" },
  { name: "P. Peter Benedicto Devantara", role: "Pastor Rekan Paroki Santo Petrus dan Paulus", place: "Mangga Besar, Jakarta", since: "15 Agt 2026", kaulAkhir: "Kaul akhir 2025" },
  { name: "P. Andreas Agung Nugroho", role: "Pastor Rekan Paroki Santa Maria Diangkat ke Surga (Katedral)", place: "Jakarta", since: "15 Agt 2026", ordination: "Imam 29 Jul 2026, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 26 Jan 2026" },
  { name: "P. Amadea Prajna Putra Mahardika", role: "Studi teologi sistematik, Jesuit School of Theology, Santa Clara University", place: "Berkeley", since: "15 Agt 2026", ordination: "Imam 29 Jul 2026, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 26 Jan 2026" },
  { name: "P. Gregorius Agung Satriyo Wibisono", role: "Staf SMA Seminari Santo Petrus Canisius", place: "Mertoyudan", since: "15 Agt 2026", ordination: "Imam 29 Jul 2026, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 7 Apr 2026, Basilica Santa Maria Maggiore, Roma" },
  { name: "P. Klaus Heinrich Raditio", role: "Pastor Rekan Gereja Paroki Internasional St. Petrus Canisius & staf STF Driyarkara", place: "Jakarta", since: "15 Agt 2026", ordination: "Imam 29 Jul 2026, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 26 Jan 2026" },
  { name: "P. Bernadus Dirgaprimawan", role: "Prefek Studi Kolese Santo Ignatius", place: "Yogyakarta", since: "15 Agt 2026", kaulAkhir: "Kaul akhir 2025" },
  { name: "P. Paulus Bambang Irawan", role: "Ekonom Kolese Santo Ignatius", place: "Yogyakarta", since: "15 Agt 2026" },
  { name: "P. Simon Arief Herdian Putra Tama", role: "Staf KPTT", place: "Salatiga", since: "15 Agt 2026" },
  { name: "P. Herman Joseph Suhardiyanto", role: "Rumah Provinsialat SJ", place: "Indonesia", since: "15 Jun 2026" },
  { name: "P. Yohanes Alis Windu Prasetya", role: "Minister Komunitas Kolese Santo Stanislaus Koskta", place: "Girisonta", since: "15 Jun 2026" },
  { name: "S. Yohanes Ignasius Setiawan", role: "Studi psikologi, Universitas Gregoriana", place: "Roma", since: "2026-2027" },
  { name: "S. Arnoldus Iga Pradipta", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "S. John Fisher Gading Winugraha", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "S. Efrem Mas Aletadeo Satya Pramuda", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "S. Realino Halford Triatmaja", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "S. Karel Amadeus Effendi", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "S. Antonius Vinsensius Egwin Gawe", role: "Formasi filsafat, STF Driyarkara", place: "Jakarta", since: "24 Jun 2026" },
  { name: "P. Joannes Abdipranata", role: "Pembimbing retret, Rumah Retret Kristus Raja", place: "Girisonta", since: "1 Jul 2026" },
  { name: "P. Bonaventura Hartaja Toto Budyarja", role: "Minister Komunitas Kolese St. Robertus Bellarminus", place: "Yogyakarta", since: "1 Jul 2026" },
  { name: "F. Y Sunari", role: "Minister Komunitas Kolese St. Ignatius", place: "Yogyakarta", since: "1 Jul 2026" },
  { name: "P. Laurentius Sutarno", role: "Pastor Rekan Gereja Paroki Santo Servatius", place: "Kampung Sawah", since: "1 Jul 2026" },
  { name: "P. Christoporus Aria Prabantara", role: "Pastor Rekan Gereja Santa Theresia", place: "Jakarta", since: "1 Jul 2026" },
  { name: "P. Andreas Sugijopranoto", role: "Konsultor Serikat Jesus Provinsi Indonesia", place: "Indonesia", since: "1 Jul 2026" },
  { name: "P. Adrianus Suyadi", role: "Anggota Konsultor Serikat Jesus Provinsi Indonesia", place: "Indonesia", since: "1 Jul 2026" },
  { name: "S. Roberthus Kalis Jati Irawan", role: "Asistensi Gereja Santo Antonius Padua & mengajar di SMK St. Mikael", place: "Purbayan / Surakarta", since: "15 Mei 2026" },
  { name: "P. Cyprianus Kuntoro Adi", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026", place: "Indonesia", since: "15 Mei 2026" },
  { name: "P. Dominico Savio Octariano Widiantoro", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026", place: "Indonesia", since: "15 Mei 2026" },
  { name: "P. Melkyor Pando", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026", place: "Indonesia", since: "15 Mei 2026" },
  { name: "S. Feliks Erasmus Arga", role: "Formasi Tahap Orientasi Kerasulan (TOK), Xavier High School", place: "Chuuk, Micronesia", since: "15 Jun 2026" },
  { name: "S. Sirilus Hari Prasetyo", role: "Formasi TOK, SMK PIKA", place: "Semarang", since: "15 Jun 2026" },
  { name: "S. Yohanes Deo Yudistiro Utomo", role: "Formasi TOK, SMA Adhi Luhur", place: "Nabire", since: "15 Jun 2026" },
  { name: "S. Beda Holy Septianno", role: "Formasi TOK, Seminari Mertoyudan", place: "Mertoyudan", since: "15 Jun 2026" },
  { name: "S. Alfonsus Ignatius Franky Njoto", role: "Formasi Teologi, Loyola School of Theology, Ateneo de Manila University", place: "Filipina", since: "25 Jun 2026" },
  { name: "S. Engelbertus Viktor Daki", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)", place: "Yogyakarta", since: "25 Jun 2026" },
  { name: "S. Klemens Yuris Widya Denanta", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)", place: "Yogyakarta", since: "25 Jun 2026" },
  { name: "S. Teilhard Aurobindo Soesilo", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)", place: "Yogyakarta", since: "25 Jun 2026" },
  { name: "S. Mikael Tri Karitasanto", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)", place: "Yogyakarta", since: "25 Jun 2026" },
  { name: "S. Leonardo Ardhani Escriva Pamungkas", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)", place: "Yogyakarta", since: "25 Jun 2026" },
  { name: "P. Hugo Bayu Hadibowo", role: "Pastor Rekan Paroki Santa Maria Bunda Allah", place: "Botong, Ketapang", since: "15 Apr 2026", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 23 Okt 2020" },
  { name: "P. Martinus Juprianto Bulu Toding", role: "Pendamping mahasiswa Universitas Sanata Dharma", place: "Yogyakarta", since: "1 Apr 2026", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 23 Okt 2020" },
  { name: "P. Harry Setianto Sunaryo", role: "Moderator SMA Kolese de Britto", place: "Yogyakarta", since: "1 Apr 2026", ordination: "Imam 31 Jul 2019, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Ignatius Windar Santoso", role: "Minister Kolese Hermanum", place: "Jakarta", since: "15 Apr 2026" },
  { name: "P. Antonius Septian Marhenanto", role: "Minister Rumah Provinsialat SJ & Koordinator Tim Komunikator Provindo", place: "Indonesia", since: "15 Apr 2026", ordination: "Imam 23 Jul 2025, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 12 Okt 2024, Gereja Gesù, Ateneo de Manila (Filipina)" },
  { name: "P. Ignatius Suryadi", role: "Minister Komunitas Beato Miguel Pro", place: "Jakarta", since: "1 Feb 2026" },
  { name: "P. Franciscus Xaverius Murti Hadi Wijayanto", role: "Co-delegatus Ongoing Formation", place: "Indonesia", since: "1 Feb 2026" },
  { name: "P. Agustinus Sarwanto", role: "Komisi Keuangan Provindo", place: "Indonesia", since: "1 Feb 2026", kaulAkhir: "Kaul akhir 2021, Kapel Bellarminus, Yogyakarta (31 Okt 2021)" },
  { name: "P. Albertus Sadhyoko Rahardjo", role: "Komisi Keuangan Provindo", place: "Indonesia", since: "1 Feb 2026" },
  { name: "P. Yusup Edi Mulyono", role: "Komisi Keuangan Provindo", place: "Indonesia", since: "1 Feb 2026" },
  { name: "P. Albertus Hani Rudi Hartoko", role: "Vikaris Parokial Paroki St. Yusup", place: "Ambarawa", since: "1 Jan 2026" },
  { name: "P. Macarius Maharsono Probho", role: "Pastor Kepala Paroki Santa Maria Diangkat ke Surga (Katedral)", place: "Jakarta", since: "1 Jan 2026" },
  { name: "P. Athanasius Kristiono Purwadi", role: "Pastor Kepala Paroki Hati Santa Perawan Maria Tak Bernoda", place: "Tangerang", since: "1 Jan 2026" },
  { name: "P. Franciscus Xaverius Dedomau Djatmiko da Gomez", role: "Pastor Kepala Paroki Santa Perawan Maria Ratu", place: "Blok Q, Jakarta", since: "1 Jan 2026" },
  { name: "P. Antonius Dhimas Hardjuna", role: "Pastor Kepala Gereja Paroki Santa Maria Bunda Allah", place: "Botong", since: "1 Jan 2026" },
  { name: "P. Ignatius Swasono", role: "Staf Campus Ministry Universitas Sanata Dharma", place: "Yogyakarta", since: "1 Jan 2026" },
  { name: "P. Justinus Sigit Prasadja", role: "Pastor Rekan Paroki Santo Robertus Bellarminus", place: "Cililitan, Jakarta", since: "1 Jan 2026", kaulAkhir: "Kaul akhir 2022, Kapel Santa Perawan Maria, RR Panti Semedi, Klaten (25 Jul 2022)" },
  { name: "P. Paulus Andri Astanto", role: "Pastor Kepala Gereja Paroki Santo Robertus Bellarminus", place: "Cililitan, Jakarta", since: "1 Jan 2026" },
  { name: "P. Yohanes Harry Kristanto", role: "Persiapan penugasan Misi Pakistan", place: "Pakistan", since: "2026", ordination: "Imam 27 Jul 2022, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 5 Mei 2022, Gereja St. Antonius Padua, Kotabaru" },
  { name: "P. Thomas Becket Gandi Hartana", role: "Sekretaris Yayasan Budi Siswa (Kolese Kanisius) & Sekretaris Eksekutif Komisi Pendidikan KWI", place: "Menteng, Jakarta", since: "1 Jan 2026" },
  { name: "P. Emanuel Baskoro Poedjinoegroho", role: "Panitia Pembangunan Kolese Xaverius", place: "Penajam Paser Utara, Kalimantan Timur", since: "1 Jan 2026" },
  { name: "P. Joannes Heru Hendarto", role: "Panitia Pembangunan Kolese Xaverius", place: "Penajam Paser Utara, Kalimantan Timur", since: "1 Jan 2026" },
  { name: "P. Joannes Moerti Yoedho Koesoemo", role: "Panitia Pembangunan Kolese Xaverius", place: "Penajam Paser Utara, Kalimantan Timur", since: "1 Jan 2026" },
  { name: "P. Johannes Adrianus Hendra Sutedja", role: "Panitia Pembangunan Kolese Xaverius", place: "Penajam Paser Utara, Kalimantan Timur", since: "1 Jan 2026" },
  { name: "P. Julius Mario Plea Lagaor", role: "Panitia Pembangunan Kolese Xaverius", place: "Penajam Paser Utara, Kalimantan Timur", since: "1 Jan 2026" },
  { name: "P. Leonardus Evert Bambang Winandoko", role: "Rektor Komunitas Jesuit Kolese Kanisius & Ketua Yayasan Budi Siswa", place: "Menteng, Jakarta", since: "1 Jan 2026" },
  { name: "P. Markus Sjamsul Wanandi", role: "Pendampingan rohani alumni Kolese Kanisius", place: "Menteng, Jakarta", since: "2023" },
  { name: "P. Mario Tomi Subardjo", role: "Pengajar Loyola School of Theology", place: "Manila", since: "1 Jan 2025" },
  { name: "P. Fransiskus Pieter Dolle", role: "Tim Promosi Panggilan", place: "Yogyakarta & Jawa Tengah", since: "1 Des 2025", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Hendricus Satya Wening Pambudi", role: "Tim Promosi Panggilan", place: "Jakarta", since: "1 Des 2025", ordination: "Imam 31 Jul 2019, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Paulus Hastra Kurdani", role: "Tim Promosi Panggilan", place: "Jakarta", since: "1 Des 2025", ordination: "Imam 27 Jul 2022, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", diakon: "Diakon 5 Feb 2022, Gereja SS Fransiskus Xaverius & Aloysius Gonzaga, Madrid" },
  { name: "F. Franciscus Xaverius Marsono", role: "Tim Promosi Panggilan untuk Bruder", place: "Indonesia", since: "1 Des 2025", kaulAkhir: "Kaul akhir 2022, Kapel Santa Perawan Maria, RR Panti Semedi, Klaten (25 Jul 2022)" },
  { name: "F. Ignatius Ulrig Jumeno", role: "Tim Promosi Panggilan untuk Bruder", place: "Indonesia", since: "1 Des 2025" },
  { name: "P. Stephanus Hari Suparwito", role: "Rektor Komunitas Kolese St. Robertus Bellarminus", place: "Yogyakarta", since: "1 Nov 2025" },
  { name: "P. Gregorius Soetomo", role: "Moderator Pemuda Katolik Komisariat Daerah DKI Jakarta", place: "Jakarta", since: "1 Okt 2025" },
  { name: "P. Petrus Sunu Hardiyanta", role: "Ketua Pengurus Yayasan Taman Tani", place: "Salatiga", since: "28 Nov 2025" },
  { name: "P. Synesius Suyitna", role: "Sekretaris Pengurus Yayasan Taman Tani", place: "Salatiga", since: "28 Nov 2025" },
  { name: "P. Andreas Aryono Mantiri", role: "Bendahara Pengurus Yayasan Taman Tani / Asisten Ekonom Provindo", place: "Salatiga", since: "28 Nov 2025", ordination: "Imam 31 Jul 2024, Gereja St. Antonius Padua, Yogyakarta", diakon: "Diakon 25 Jan 2024, Kapel Seminari Tinggi St. Paulus, Kentungan" },
  { name: "P. Robertus Sigit Adi Nugroho", role: "Menunggu penugasan baru, Provinsialat SJ", place: "Indonesia", since: "1 Mei 2025" },
  { name: "P. Joannes Maryana", role: "Pastor Rekan Paroki Santa Theresia & Ketua Dewan Paroki Harian (2025-2028); mantan Rektor Seminari Mertoyudan & Kepala Bagian Keuangan KWI", place: "Menteng, Jakarta Pusat", since: "2025" },
  { name: "P. Stefanus Hendrianto", role: "Imam Jesuit Provinsi Jesuits West (Amerika Serikat); ditahbiskan 8 Juni 2019, Gereja Our Lady of La Vang, Portland, Oregon; mantan aktivis pro-demokrasi 1998", place: "Amerika Serikat", since: "2019", ordination: "Imam 8 Jun 2019, Gereja Our Lady of La Vang, Portland, Oregon (Uskup Agung Alexander Sample). Jesuit Provinsi Jesuits West, bukan Provinsi Indonesia.", catatan: "Studi: hukum UGM, Utrecht & University of Washington; novisiat di AS (2009), kaul pertama 2011, Loyola Chicago, Boston College." },
  { name: "P. Heinrich Angga Indraswara", role: "Imam Jesuit, bertugas di Paroki St. Yohanes Maria Vianney, Jakarta (ditahbiskan 2018)", place: "Jakarta", since: "2018", ordination: "Imam 25 Jul 2018, Gereja St. Antonius Padua, Kotabaru, Yogyakarta", catatan: "Misa perdana 5 Agt 2018, Gereja Hati Kudus, Kramat, Jakarta Pusat. Ayahnya Muslim, ibunya Prof. Karlina Supelli." },
  { name: "P. Christoforus Kristiono Puspo", role: "ATMI Recycle Studio (ARS)", place: "Jakarta", since: "2026", kaulAkhir: "Kaul akhir 2025, Kapel Kolese Kanisius, Jakarta (Agu 2025)" },
  { name: "P. Agustinus Winaryanta", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2025", kaulAkhir: "Kaul akhir 2025, Kapel Kolese Kanisius, Jakarta (Agu 2025)" },
  { name: "P. Alexander Koko Siswijayanto", role: "Direktur Campus Ministry, Kolese Kanisius", place: "Jakarta", since: "2026", kaulAkhir: "Kaul akhir 2025" },
  { name: "P. Christoforus Bayu Risanto", role: "Ahli Meteorologi, Vatican Observatory & Research Associate, University of Arizona", place: "Vatikan / Arizona, AS", since: "2026", kaulAkhir: "Kaul akhir 2025" },
  { name: "P. Thomas Septi Widhiyudana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2025", kaulAkhir: "Kaul akhir 2025, Kapel Kolese Kanisius, Jakarta (Agu 2025)" },
  { name: "P. Nicolaus Devianto Fajar Trinugroho", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2024", kaulAkhir: "Kaul akhir 2024, Kapel St. Robertus Bellarminus, Mrican, Yogyakarta (19 Mar 2024)" },
  { name: "P. Stephanus Advent Novianto", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2024", kaulAkhir: "Kaul akhir 2024, Kapel St. Robertus Bellarminus, Mrican, Yogyakarta (19 Mar 2024)" },
  { name: "P. Benedictus Cahyo Christanto", role: "Pastor Kepala Paroki St. Yusuf Gedangan", place: "Semarang", since: "2024", kaulAkhir: "Kaul akhir 2024" },
  { name: "P. Aluisius Pramudya Daniswara", role: "Pastor Paroki Blok B, Keuskupan Agung Jakarta", place: "Jakarta", since: "2025", kaulAkhir: "Kaul akhir 2024" },
  { name: "P. Rikhardus Sani Wibowo", role: "Presenter, Ignatian Leadership Program, SMA Adhi Luhur", place: "Nabire, Papua", since: "2026", kaulAkhir: "Kaul akhir 2024" },
  { name: "P. Joseph Mangatur Mangisi Tua Situmorang", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2023", kaulAkhir: "Kaul akhir 2023, Gereja Santa Theresia, Bongsari, Semarang (Feb 2024)" },
  { name: "P. Eduardus Didik Chahyono Widyatama", role: "Pastor Paroki St. Theresia", place: "Bongsari, Semarang", since: "2024", kaulAkhir: "Kaul akhir 2023" },
  { name: "P. Alexander Hendra Dwi Asmara", role: "Tim pengajar kateketik Universitas Sanata Dharma, Novisiat St. Stanislaus & Staf Ahli Katekese Komisi Kateketik KWI", place: "Yogyakarta / Jakarta", since: "2025", kaulAkhir: "Kaul akhir 2023" },
  { name: "P. Yulius Eko Sulistyo", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2022", kaulAkhir: "Kaul akhir 2021, Gereja SPMR Blok Q, Jakarta (2 Feb 2022)" },
  { name: "P. Albertus Buddy Haryadi", role: "Wakil Direktur I Bidang Kesiswaan, Kolese Kanisius", place: "Menteng, Jakarta", since: "2022", kaulAkhir: "Kaul akhir, Gereja SPMR Blok Q, Jakarta (2 Feb 2022)" },
  { name: "P. Antonius Sumarwan", role: "Koordinator Nasional Jaringan Doa Bapa Suci Sedunia (PWPN) Indonesia", place: "Indonesia", since: "2026", kaulAkhir: "Kaul akhir, Gereja SPMR Blok Q, Jakarta (2 Feb 2022)" },
  { name: "P. Aluisius Dian Permana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2021", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Alfonsus Ardi Jatmiko", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2021", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Evodius Sapto Jati Nugroho", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "2021", ordination: "Imam 19 Agt 2021, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Antonius Bagas Prasetya", role: "Vikaris Parokial, Paroki Santo Antonius Padua", place: "Purbayan, Surakarta", since: "2024", ordination: "Imam 31 Jul 2024, Gereja St. Antonius Padua, Yogyakarta" },
  { name: "P. Tiro Angelo Daenuwy", role: "Moderator SMK Kolese Mikael", place: "Surakarta", since: "2024", ordination: "Imam 31 Jul 2024, Gereja St. Antonius Padua, Yogyakarta" },
  { name: "P. Isodorus Bangkit Susetyo Adi Nugroho", role: "Staf SMA YPPK Adhi Luhur", place: "Nabire, Papua", since: "2025", ordination: "Imam 23 Jul 2025, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Leo Perkasa Tanjung", role: "Studi Kitab Suci di Biblicum", place: "Roma", since: "2025", ordination: "Imam 23 Jul 2025, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Jacobus Aditya Christie Manggala", role: "Direktur Campus Ministry, Universitas Sanata Dharma", place: "Yogyakarta", since: "2025", ordination: "Imam 23 Jul 2025, Gereja St. Antonius Padua, Kotabaru, Yogyakarta" },
  { name: "P. Roberthus (Robert) Rimmin", role: "Imam Jesuit senior; karya misi di Timor Leste sejak tahbisan", place: "Timor Leste", since: "1999", ordination: "Imam 14 Jul 1999, Yogyakarta (bersama P. Tarcisius Dewanto dkk.)", catatan: "Imam senior, bukan mahasiswa/skolastik dalam formasi." },
  { name: "S. Adrianus Raditya Indriyatno", role: "Mahasiswa filsafat, STF Driyarkara (tinggal di Kolese Hermanum)", place: "Jakarta", since: "2026" },
  { name: "S. Septian Kurniawan", role: "Mahasiswa teologi tahun pertama, FTW (Kolese St. Ignatius / Kolsani)", place: "Yogyakarta", since: "2026" },
  { name: "Br. Nicolaus David Kristianto", role: "Bruder Jesuit; pembaharu kaul, Retret Bruder JCAP, Girisonta", place: "Girisonta", since: "2024" },
  { name: "Br. Yohanes Sarju", role: "Kepala Departemen Pengembangan SDM – Pelayanan Umum – Tenaga Gereja, KWI", place: "Jakarta (KWI)", since: "2020", catatan: "Marga/belakang tidak dipublikasikan di jesuits.id." },
  { name: "P. Fransiskus Wawan Setyadi", role: "Dosen filsafat & Wakil Ketua III STF Driyarkara; pelatih Komisi Komunikasi Sosial (Komsos) KWI", place: "Jakarta", since: "2026", kaulAkhir: "Kaul akhir 1 Jan 2021, Gereja St. Antonius Padua, Surakarta (dekrit P. Jenderal 15 Jun 2020)" },
  { name: "P. Baskara T. Wardaya", role: "PRAKSIS (Jesuit Centre for Research & Advocacy); bermukim di Residensi Kolese Kanisius", place: "Menteng, Jakarta", since: "2024" },
  { name: "P. Ignatius Ismartono", role: "Pendampingan rohani (Talitha Kum / Sahabat Insan), Kolese Kanisius", place: "Menteng, Jakarta", since: "2024" },
  { name: "Br. Matheus Sugiyono", role: "Direktur Pusat Pelatihan Edukasi Kolese Kanisius & Ekonom Komunitas", place: "Menteng, Jakarta", since: "2024" },
  { name: "Fr. Leander Emanuel Arya Wikan Prabantara", role: "Staf Wakil Direktur I Bidang Kesiswaan, Kolese Kanisius (2025-2027)", place: "Menteng, Jakarta", since: "2025" },
  { name: "P. Eduard C. Ratu Dopo", role: "Kepala Sekolah SMA Kolese Gonzaga", place: "Jakarta", since: "2024" },
  { name: "P. Yulius Suroso", role: "Wakil Kepala Sekolah Bidang Kesiswaan, SMA Kolese Gonzaga", place: "Jakarta", since: "2024" },
  { name: "P. Tiburtius Agus Sriyono", role: "Pembina/direksi Politeknik Industri ATMI Cikarang & ATMI Surakarta", place: "Cikarang / Solo", since: "2020" },
  { name: "P. Yakobus Rudiyanto", role: "Ketua Yayasan Karya ATMI", place: "Cikarang", since: "2022" },
  { name: "P. Franz Magnis-Suseno", role: "Dosen Program Doktor Filsafat, STF Driyarkara", place: "Jakarta", since: "" },
  { name: "P. Justinus Sudarminta", role: "Ketua Senat Dosen & pengajar S2/S3, STF Driyarkara", place: "Jakarta", since: "" },
  { name: "P. Johanes Haryatmoko", role: "Dosen/peneliti (STF Driyarkara / Universitas Sanata Dharma)", place: "Jakarta / Yogyakarta", since: "" },
  { name: "P. Gabriel Possenti Sindhunata", role: "Penulis; redaksi majalah Basis; dosen filsafat", place: "Yogyakarta", since: "" },
  { name: "P. A. Setyo Wibowo", role: "Dosen filsafat, STF Driyarkara", place: "Jakarta", since: "" },
  { name: "Kardinal Ignatius Suharyo", role: "Uskup Agung Jakarta (Kardinal, S.J.)", place: "Jakarta", since: "2010" },
  { name: "P. Bernardus Agus Rukiyanto", role: "Wakil Lembaga Kateketik (Perdikkati), Komisi Kateketik KWI", place: "Jakarta (KWI)", since: "" },
  { name: "P. Antonius Vico Christiawan", role: "Sekretaris Komisi Pendidikan KWI", place: "Jakarta (KWI)", since: "" },

  /* ---------- TAMBAHAN (dari halaman Komunitas & arsip konten jesuits.id) ---------- */
  { name: "P. Benedictus Hari Juliawan", role: "Superior Komunitas Kolese St. Robertus Bellarminus; Provinsial SJ 2020–2026", place: "Yogyakarta", since: "2026", ordination: "Doktor Development Studies, Universitas Oxford" },
  { name: "P. Antonius Gustawan", role: "Superior Komunitas Kolese Johanes de Britto", place: "Yogyakarta", since: "2026" },
  { name: "P. Yosephus Ispuroyanto Iswarahadi", role: "Superior Komunitas Bener", place: "Bener, Purworejo", since: "2026" },
  { name: "P. Laurentius Priyo Poedjiono", role: "Superior Komunitas Santo Stanislaus", place: "Girisonta", since: "2026" },
  { name: "P. Bambang Alfred Sipayung", role: "Superior Komunitas Rumah Provinsialat SJ", place: "Semarang", since: "2026" },
  { name: "P. Yohanes Sudriyanto", role: "Superior Komunitas Kolese Le Cocq d'Armandville", place: "Indonesia", since: "2026" },
  { name: "P. Leo Agung Sardi", role: "Superior Komunitas Seminari St. Petrus Kanisius", place: "Mertoyudan", since: "2026" },
  { name: "P. Simon Petrus Bambang Ponco Santosa", role: "Superior Komunitas Beato Miguel Pro", place: "Jakarta", since: "2026" },
  { name: "P. Antonius Dieng Karnedi", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Ignatius Dio Ernanda Johandika", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Leslie Joseph Bingkasan", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Danang Bramasti", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Christoforus Iuliano Mesaroga", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Ignatius Damar Adi Wicaksana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Agustinus Rudy Chandra Wijaya", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Ignatius Suryadi Prajitno", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Ignatius Drajat Soesilo", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Yohanes Paulus Sunari", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "S. Laurensius Herdian Pambudi", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "S. Lambertus Alfred", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "S. Daud Kefas Raditya", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "S. Arnold Lintang Yanviero", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "S. Wahyu Mega", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan", place: "Indonesia", since: "" },
  { name: "P. Yohanes Deodatus", role: "Pastor Rekan Gereja Katedral Jakarta (komunitas Beato Rupert Mayer)", place: "Jakarta", since: "" },
  { name: "P. Bernardus Christian Triyudo Prastowo", role: "Pastor Rekan Gereja Katedral Jakarta (komunitas Beato Rupert Mayer)", place: "Jakarta", since: "" },
];

/* ---------- TELAH BERPU-LANG / MENINGGAL (dari Obituari) ----------
   Field: name, title, died, born, entered, firstVows, ordination, vows, studies */
const deceasedJesuits = [
  {
    name: "Adrianus Herry Wijayanto, S.J.", title: "Pater", died: "18 Juni 2026 (usia 60)",
    born: "11 Januari 1966, Cimahi, Jawa Barat",
    entered: "5 Juli 1988 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 Juli 1990",
    ordination: "Imam 14 Juli 1999, di Gereja Santo Antonius Padua, Yogyakarta (Diakon 4 April 1999, Kapel Seminari Tinggi St. Paulus, Kentungan)",
    vows: "8 Desember 2012",
    studies: "Filsafat STF Driyarkara, Jakarta (1990–1994); TOK Civita Youth Camp (1994–1996); Teologi Fakultas Teologi Wedabhakti–Universitas Sanata Dharma, Yogyakarta (1996–1999)."
  },
  {
    name: "Bernhard Kieser, S.J.", title: "Pater", died: "6 Juni 2026 (usia 87)",
    born: "28 September 1938, Bruchsal, Jerman",
    entered: "25 April 1957 — Novisiat Neuhausen, Jerman",
    firstVows: "27 April 1959",
    ordination: "Imam 5 Juli 1968, Yogyakarta (Diakon 23 Mei 1968; tonsura & tahbisan rendah 1962, Berchmans Kolleg, München)",
    vows: "15 Agustus 1974, Yogyakarta",
    studies: "Filsafat Sekolah Tinggi Filsafat München, Jerman (1957–1962); TOK Paroki Muntilan (1963–1965); Teologi di Yogyakarta & Frankfurt (1965–1969); Doktoral teologi moral Frankfurt & Innsbruck (1970–1973)."
  },
  {
    name: "Henricus van Opzeeland, S.J.", title: "Pater", died: "18 Juni 2019",
    born: "", entered: "", firstVows: "", ordination: "", vows: "",
    studies: "Misionaris Jesuit. (Detail riwayat tidak tersedia di arsip situs.)"
  },
  {
    name: "Adolf Heuken, S.J.", title: "Pater", died: "25 Juli 2019 (usia 90)",
    born: "", entered: "", firstVows: "", ordination: "", vows: "",
    studies: "Misionaris, penulis buku rohani & bahasa Indonesia. (Detail riwayat tidak tersedia di arsip situs.)"
  },
  {
    name: "Alexander Dirjasusanta, S.J.", title: "Pater", died: "13 November 2023 (usia 85)",
    born: "24 Februari 1938, Kulon Progo",
    entered: "7 September 1958 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 September 1960",
    ordination: "Imam 16 Desember 1970, Yogyakarta (Diakon 9 September 1970)",
    vows: "24 Desember 1979 — Gereja Santo Athanasius, Karangpanas, Semarang (Spiritual Coadjutor)",
    studies: "Seminari Menengah St. Petrus Canisius, Magelang; Filsafat Pune, India (1962–1965); Teologi Fakultas Teologi Wedabhakti–USD (1968–1972); Kursus Spiritualitas Sadana, India."
  },
  {
    name: "Andreas Yuniko Poerdianto, S.J.", title: "Pater", died: "29 Juli 2021 (usia 53)",
    born: "22 Juni 1968, Situbondo, Jawa Timur",
    entered: "1 Juli 2000 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "2 Juli 2002",
    ordination: "Imam 25 Juli 2013, Gereja Santo Antonius Padua, Yogyakarta (Diakon 24 November 2012, Xavier College, Australia)",
    vows: "Belum tercatat (wafat menjelang kaul kekal)",
    studies: "Institut Teknologi Surabaya (ITS) (1989–1995); Filsafat STF Driyarkara (2003–2007); Teologi Jesuit Theological College, Melbourne, Australia (2009–2013)."
  },
  {
    name: "Antonius Sutanto, S.J.", title: "Pater", died: "1 Maret 2022 (usia 83)",
    born: "23 Agustus 1938, Semarang",
    entered: "7 September 1959 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 September 1961",
    ordination: "Imam 6 Desember 1971, Gereja Santo Antonius Padua, Kotabaru, Yogyakarta (Diakon 5 Desember 1971)",
    vows: "29 Agustus 1982 — Gereja St. Fransiskus Xaverius, Tanjung Priok, Jakarta",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat Pune, India (1963–1966); Teologi Yogyakarta (1969–1972); Musik Institut van Katholieke Kerkmuziek, Utrecht, Belanda (1973–1977)."
  },
  {
    name: "Augustinus Mangunhardjana, S.J.", title: "Pater", died: "4 Februari 2025 (usia 81)",
    born: "28 Agustus 1943, Sleman",
    entered: "7 September 1963 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 September 1965",
    ordination: "Imam 3 Desember 1975, Yogyakarta (Diakon 17 September 1975)",
    vows: "16 Februari 1983 — Kapel Provinsialat SJ, Semarang (profes)",
    studies: "Seminari Menengah St. Petrus Canisius, Magelang; Filsafat Pune, India (1966–1970); Teologi Fakultas Teologi Wedabhakti–USD (1972–1975); Studi Adult Education (magister), Dekalb, Illinois, USA (1986–1988)."
  },
  {
    name: "Bernardinus Herry Priyono, S.J.", title: "Pater", died: "21 Desember 2020 (usia 60)",
    born: "31 Mei 1960, Yogyakarta",
    entered: "15 Juli 1979",
    firstVows: "16 Juli 1981",
    ordination: "Imam 27 Juli 1992, Gereja St. Ignatius (Padua), Kotabaru, Yogyakarta",
    vows: "31 Juli 2009 — Kapel St. Ignatius Loyola, Semarang (Profesi Empat Kaul)",
    studies: "Filsafat STF Driyarkara (1981–1984); Sosiologi University of the Philippines, Manila (1984–1989); Teologi Fakultas Teologi Wedabhakti, Yogyakarta (1989–1992); Doktorat Politik-Ekonomi London School of Economics, UK (1994–2003)."
  },
  {
    name: "Bruno Herman Tjahja, S.J.", title: "Pater", died: "2 Mei 2025 (usia 63)",
    born: "21 Mei 1961, Semarang",
    entered: "7 Juli 1981 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 Juli 1983",
    ordination: "Imam 29 Juli 1994, Gereja Santo Antonius Kotabaru, Yogyakarta (Diakon 16 Juni 1994)",
    vows: "25 Juli 2022 — Kapel Rumah Retret Panti Semedi, Klaten (Spiritual Coadjutor)",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat STF Driyarkara (1983–1986); Teologi FTW Wedabhakti–USD (1989–1994); penyelesaian lisensiat teologi (1996–1998)."
  },
  {
    name: "Ferdinandus Yuswar Riyana, S.J.", title: "Pater", died: "10 Desember 2024 (usia 72)",
    born: "7 Juli 1952, Klaten",
    entered: "15 Juli 1980 — Novisiat St. Stanislaus, Girisonta",
    firstVows: "16 Juli 1982",
    ordination: "Imam 29 Juli 1991, Gereja St. Antonius Kotabaru, Yogyakarta (Diakon 25 Januari 1991)",
    vows: "3 Desember 1998 — Kapel SAV Puskat, Yogyakarta (Coadjutor Spiritualis)",
    studies: "Akademi Bahasa Asing Negeri, Jakarta; Filsafat STF Driyarkara, Jakarta (1982–1985); Teologi Yogyakarta (1988–1992)."
  },
  {
    name: "Florentinus Subroto Widjojo, S.J.", title: "Pater", died: "22 Juni 2024 (usia 84)",
    born: "29 Oktober 1939, Pengasih-Wates, Kulon Progo",
    entered: "7 September 1959 — Novisiat St. Stanislaus, Girisonta",
    firstVows: "8 September 1961",
    ordination: "Imam 16 Desember 1970, Gereja St. Antonius Padua, Yogyakarta (Diakon 9 September 1970)",
    vows: "15 Agustus 1982, Rawasari, Jakarta (Profesi Empat Kaul)",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat Kolese de Nobili, Pune, India (1963–1966); Teologi IFT Kentungan–USD (1968–1971); Studi Psikologi Sosial Ateneo de Manila (1972–1975)."
  },
  {
    name: "Franciscus Xaverius Arko Sudiono, S.J.", title: "Pater", died: "12 Desember 2025 (usia 69)",
    born: "28 Juli 1956, Yogyakarta",
    entered: "15 Juli 1979 — Novisiat SJ Girisonta",
    firstVows: "16 Juli 1981",
    ordination: "Imam 24 Juli 1989, Gereja St. Antonius Padua, Yogyakarta (Diakon 25 Januari 1989)",
    vows: "7 September 1992 — Gereja St. Ignatius, Jakarta",
    studies: "SMA Kolese de Britto, Yogyakarta; Filsafat STF Driyarkara (1981–1984); TOK Xavier High School, Chuuk, Micronesia (1984–1986); Teologi FTW, Yogyakarta (1986–1989)."
  },
  {
    name: "Franciscus Xaverius Mudji Sutrisno, S.J.", title: "Pater", died: "28 Desember 2025 (usia 71)",
    born: "12 Agustus 1954, Surakarta",
    entered: "5 Januari 1973 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "1 Januari 1975",
    ordination: "Imam 30 Desember 1982, Gereja Santo Antonius Kotabaru, Yogyakarta (Diakon 30 Oktober 1982)",
    vows: "31 Juli 1989 — Gereja Santo Antonius Padua, Kotabaru, Yogyakarta",
    studies: "Seminari Santo Petrus Canisius, Mertoyudan; Filsafat STF Driyarkara (1975–1976); Filsafat Universitas Gregoriana, Roma (1976–1979) & Doktorat filsafat (1984–1987); Teologi FTW, Yogyakarta (1979–1982)."
  },
  {
    name: "Hadrian Handy Lenggawa, S.J.", title: "Pater", died: "28 Oktober 2023 (usia 65)",
    born: "12 Oktober 1958, Brebes",
    entered: "25 Mei 1999 — Loyola Jesuit Novitiate, Singapura",
    firstVows: "±2001",
    ordination: "Imam 29 Juli 2009, Gereja St. Antonius Kotabaru, Yogyakarta (Diakon 18 April 2009, Katedral Jakarta)",
    vows: "Tidak disebut",
    studies: "Politeknik Aachen, Jerman (Teknologi Informasi, 1988–1989); Filsafat STF Driyarkara (2002–2005); TOK SMK PIKA Semarang; Teologi STF Driyarkara (2006–2009)."
  },
  {
    name: "Ignatius Dradjat Soesilo, S.J.", title: "Pater", died: "27 Juni 2023 (usia 57)",
    born: "18 Desember 1965, Kediri",
    entered: "7 Juli 1985 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 Juli 1987",
    ordination: "Imam 30 Juli 1997, Yogyakarta (Diakon 15 Juni 1997, Dili)",
    vows: "31 Oktober 2021 — Kolese Bellarminus, Yogyakarta (Spiritual Coadjutor)",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat STF Driyarkara (1987–1991); Teologi FTW–Universitas Sanata Dharma (1993–1997)."
  },
  {
    name: "Joannes Salib Suci Prapta Diharja, S.J.", title: "Pater", died: "12 September 2022 (usia 69)",
    born: "23 November 1952, Klaten",
    entered: "31 Desember 1973 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "1 Januari 1976",
    ordination: "Imam 21 Juli 1988, Gereja St. Antonius Padua, Purbayan, Surakarta (Diakon 27 Januari 1988)",
    vows: "2 Februari 1995 — Kapel STFK Pradnyawidya, Yogyakarta (Spiritual Coadjutor)",
    studies: "SPG van Lith, Muntilan; Filsafat STF Driyarkara (1976–1978); Bahasa & Sastra Indonesia, Universitas Indonesia (1979–1985); Teologi Fakultas Teologi Wedabhakti (1985–1988)."
  },
  {
    name: "Joannes Subagya, S.J.", title: "Pater", died: "14 November 2020 (usia 82)",
    born: "1 Juli 1938, Semarang",
    entered: "7 September 1959 — Novisiat St. Stanislaus Kostka, Girisonta",
    firstVows: "8 September 1961",
    ordination: "Imam 8 Desember 1972, Yogyakarta (Diakon 7 Desember 1972)",
    vows: "2 Februari 1981 (Profesi Empat Kaul)",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat Pune, India (1962–1965); TOK IKIP Sanata Dharma (1965–1969); Teologi Yogyakarta (1970–1973)."
  },
  {
    name: "Karl-Edmund Prier, S.J.", title: "Pater", died: "21 Januari 2024 (usia 86)",
    born: "18 September 1937, Weinheim, Jerman",
    entered: "26 April 1957, Neuhausen, Jerman",
    firstVows: "27 April 1959",
    ordination: "Imam 18 Desember 1969, Yogyakarta (Diakon 2 September 1969)",
    vows: "2 Januari 1975, Yogyakarta (Profesi Empat Kaul)",
    studies: "Filsafat Neuhausen (1959–1962); Guru musik Feldkirch (1962–1963); Teologi Yogyakarta (1967–1970)."
  },
  {
    name: "Leonard Smit, S.J.", title: "Pater", died: "29 Januari 2022 (usia 80)",
    born: "30 Mei 1941, Breda, Belanda",
    entered: "7 September 1962 — Novisiat Mariendaal",
    firstVows: "8 September 1964",
    ordination: "Imam 8 Desember 1973, Amsterdam, Belanda (Diakon 7 Desember 1972, Yogyakarta)",
    vows: "2 Februari 1981, Yogyakarta (Profesi Empat Kaul)",
    studies: "Filsafat Kolese Berchmanianum (1964–1967); Bahasa Indonesia IKIP Sanata Dharma (1969); Teologi IFT Kentungan–FTW, Yogyakarta (1970–1973)."
  },
  {
    name: "Markus Yumartana, S.J.", title: "Pater", died: "7 Agustus 2025 (usia 60)",
    born: "27 April 1965, Kokap, Kulon Progo",
    entered: "7 Juli 1985 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 Juli 1987",
    ordination: "Imam 28 Juli 1995, Gereja Santo Antonius Padua, Kotabaru, Yogyakarta (Diakon 18 April 1995, Roma)",
    vows: "20 Juli 2009 — Kapel Kampus III Universitas Sanata Dharma, Paingan, Yogyakarta",
    studies: "Seminari Menengah Santo Petrus Canisius, Magelang; Filsafat STF Driyarkara (1987–1991); Teologi & lisensiat Universitas Gregoriana, Roma (1992–1997); Studi pendidikan agama Ateneo de Manila (1999–2005)."
  },
  {
    name: "Michael Sastrapratedja, S.J.", title: "Pater", died: "17 Februari 2024 (usia 80)",
    born: "22 Oktober 1943, Kepil, Wonosobo",
    entered: "7 September 1963 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "8 September 1965",
    ordination: "Imam 3 Desember 1974, Gereja Santo Antonius Kotabaru, Yogyakarta",
    vows: "6 Februari 1981 — Kolese Hermanum, Jakarta (profes)",
    studies: "Seminari Menengah Santo Petrus Canisius, Mertoyudan; Filsafat Fakultas Kepausan Athenaeum, Pune, India (1966–1969); Teologi FTW–USD (1971–1974); Doktorat filsafat Universitas Gregoriana, Roma (1975–1979)."
  },
  {
    name: "P.S. Hary Susanto, S.J.", title: "Pater", died: "9 September 2022 (usia 67)",
    born: "25 Oktober 1954, Situbondo, Jawa Timur",
    entered: "31 Januari 1975 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "1 Januari 1978",
    ordination: "Imam 21 Juli 1988, Gereja St. Antonius, Purbayan, Surakarta (Diakon 28 Maret 1988, Gereja Gesu, Roma)",
    vows: "31 Juli 2005 — Gereja Santo Antonius Padua, Purbayan (Spiritual Coadjutor)",
    studies: "Filsafat STF Driyarkara, Jakarta (1978–1985); Teologi & Studi Moral Universitas Gregoriana, Roma (1985–1997)."
  },
  {
    name: "Paulus Wiederkehr, S.J.", title: "Bruder", died: "5 Juli 2019",
    born: "", entered: "", firstVows: "", ordination: "", vows: "",
    studies: "Bruder Jesuit. (Detail riwayat tidak tersedia di arsip situs.)"
  },
  {
    name: "Petrus Canisius Hardjawardaja, S.J.", title: "Bruder", died: "8 Februari 2026 (usia 88)",
    born: "27 Mei 1937, Sleman",
    entered: "7 Januari 1960 — Novisiat St. Stanislaus, Girisonta",
    firstVows: "8 September 1962, Kolese Stanislaus, Girisonta",
    ordination: "Bruder (tidak ditahbiskan)",
    vows: "2 Februari 1972 — Seminari Menengah Santo Petrus Canisius, Mertoyudan",
    studies: "Sekolah Teknik Pertama Kanisius Muntilan; Sekolah Teknik Negeri Magelang; kursus permesinan, Semarang."
  },
  {
    name: "Petrus Pramudyarkara Witonowarso, S.J.", title: "Pater", died: "26 Januari 2026 (usia 65)",
    born: "27 Oktober 1960, Ambarawa",
    entered: "19 Juli 1980 — Novisiat Santo Stanislaus, Girisonta",
    firstVows: "16 Juli 1982",
    ordination: "Imam 29 Juli 1992, Gereja Santo Antonius Padua, Yogyakarta (Diakon 3 Juni 1992)",
    vows: "26 November 2011 — Kapel Santo Aloysius Gonzaga, Provinsialat SJ, Semarang",
    studies: "SMA Seminari St. Petrus Canisius, Mertoyudan; Filsafat STF Driyarkara (1982–1985); Teologi FTW–USD (1988–1992); Ilmu Politik Marquette University, Wisconsin, USA (2000–2002)."
  },
  {
    name: "Philippus S. Mulyoharjono, S.J.", title: "Bruder", died: "6 Maret 2019",
    born: "", entered: "", firstVows: "", ordination: "", vows: "",
    studies: "Bruder Jesuit. (Detail riwayat tidak tersedia di arsip situs.)"
  },
  {
    name: "Pius Kirja Utama, S.J.", title: "Bruder", died: "13 Januari 2024 (usia 74)",
    born: "4 Mei 1949, Promasan, Kulon Progo",
    entered: "31 Desember 1976 — Novisiat Serikat Jesus, Girisonta",
    firstVows: "Tidak disebut",
    ordination: "Bruder (tidak ditahbiskan)",
    vows: "31 Juli 1990 — Gereja St. Antonius, Kotabaru, Yogyakarta",
    studies: "SPG Boro; Kateketik STFKat Pradnyawidya, Yogyakarta (1979–1981)."
  },
  {
    name: "Romualdus Maryono, S.J.", title: "Pater", died: "12 November 2020 (usia 61)",
    born: "7 Februari 1959, Wonosobo",
    entered: "7 Juli 1986 — Novisiat St. Stanislaus Kostka, Girisonta",
    firstVows: "6 Juli 1988",
    ordination: "Imam 30 Juli 1997, Gereja St. Antonius Padua, Yogyakarta (Diakon 16 Juni 1997, Seminari Bunda Maria Fatima, Dili)",
    vows: "7 September 2004 — Gereja St. Yusup, Gedangan",
    studies: "SPG Pangudi Luhur; Filsafat STF Driyarkara (1988–1992); Teologi FTW–USD, Yogyakarta (1994–1997)."
  },
  {
    name: "Romualdus Priyarsa, S.J.", title: "Bruder", died: "10 Februari 2019 (usia 72)",
    born: "6 Juni 1946", entered: "", firstVows: "", ordination: "", vows: "",
    studies: "Bruder Jesuit. (Detail riwayat tidak tersedia di arsip situs.)"
  },
  {
    name: "Stefanus Bagus Aris Rudiyanto, S.J.", title: "Pater", died: "1 Oktober 2020 (usia 40)",
    born: "16 Agustus 1980, Klaten",
    entered: "1 Juli 1999 — Novisiat St. Stanislaus Kostka, Girisonta",
    firstVows: "3 Juli 2001",
    ordination: "Imam 28 Juli 2010, Gereja St. Antonius Padua, Yogyakarta (Diakon 10 April 2010, Kapel Seminari Tinggi St. Paulus, Kentungan)",
    vows: "Belum diucapkan (wafat sebelum 1 Januari 2021)",
    studies: "Seminari Menengah St. Petrus Canisius, Mertoyudan; Filsafat STF Driyarkara (2001–2005); Teologi FTW–USD, Yogyakarta (2007–2010)."
  },
  {
    name: "Stevanus Prihana, S.J.", title: "Bruder", died: "21 Desember 2020 (usia 45)",
    born: "22 Agustus 1975, Sleman",
    entered: "22 Juni 2011",
    firstVows: "24 Juni 2013 — Gereja St. Stanislaus Kostka, Ungaran",
    ordination: "Bruder (tidak ditahbiskan)",
    vows: "Tidak disebut",
    studies: "SMEA Negeri V, Tempel, Sleman; Filsafat STF Driyarkara (2013–2015); S1 Seni Pedalangan, Institut Seni Indonesia (ISI) Yogyakarta (2015–2019)."
  },
  {
    name: "Theodor Wolf, S.J.", title: "Pater", died: "17 Januari 2021 (usia 76)",
    born: "Laudenbach, Jerman",
    entered: "14 September 1965, Neuhausen, Jerman",
    firstVows: "16 September 1967",
    ordination: "Imam 3 Desember 1975, Gereja St. Antonius Kotabaru, Yogyakarta",
    vows: "Tidak disebut",
    studies: "Gymnasium Miltenberg & Volkersberg, Jerman; Filsafat Pullach, Jerman (1967–1969); TOK St. Blasien College, Jerman (1969–1970); Teologi Fakultas Teologi Wedabhakti, Yogyakarta."
  },
  {
    name: "Wolfgang Bock Kastowo, S.J.", title: "Pater", died: "16 November 2023 (usia 88)",
    born: "14 Januari 1935, Berlin, Jerman",
    entered: "14 September 1960 — Novisiat Neuhausen, Esslingen, Stuttgart, Jerman",
    firstVows: "14 September 1962",
    ordination: "Imam 18 Desember 1969, Gereja Santo Antonius, Yogyakarta (Diakon 16 Desember 1969)",
    vows: "17 November 1977 — Gereja Santo Antonius, Purbayan, Surakarta (Spiritual Coadjutor)",
    studies: "Filsafat Jerman (1962–1965); Bahasa Jawa & Indonesia Kolese Santo Ignatius, Yogyakarta (dari 1966); Teologi FTW–USD, Yogyakarta (1967–1970)."
  },
  {
    name: "Yusuf Bilyarta Mangunwijaya, S.J.", title: "Pater", died: "10 Februari 1999 (usia 69)",
    born: "18 Mei 1929, Ambarawa",
    entered: "Masuk Serikat Jesus (memicu keimamatan)",
    firstVows: "",
    ordination: "Imam, ditahbiskan di Belanda (Jesuit Provinsi Indonesia)",
    vows: "",
    studies: "Arsitek, sastrawan & budayawan; dikenal sebagai 'Romo Mangun'; karya di Kalianyar, Wonosari, dan tepi Sungai Code, Yogyakarta; peraih Magsaysay serta gelar kehormatan."
  },
  {
    name: "Nicolaus Driyarkara, S.J.", title: "Pater", died: "11 Februari 1967 (usia 53)",
    born: "13 Juni 1913, Yogyakarta",
    entered: "Masuk Serikat Jesus (Jesuit Provinsi Indonesia)",
    firstVows: "",
    ordination: "Imam Jesuit",
    vows: "",
    studies: "Doktor filsafat pertama dari Indonesia; pendiri Sekolah Tinggi Filsafat (STF) Driyarkara, Jakarta — nama sekolah diambil dari namanya; tokoh pendidikan & filsafat."
  },
  {
    name: "Albertus Soegijapranata, S.J.", title: "Mgr.", died: "22 Juli 1963 (usia 66)",
    born: "25 November 1896, Surakarta",
    entered: "Masuk Serikat Jesus (Jesuit Provinsi Belanda)",
    firstVows: "",
    ordination: "Imam Jesuit; ditahbiskan Uskup pada 1940",
    vows: "",
    studies: "Uskup Semarang (1940–1963); uskup pribumi pertama di Indonesia; pahlawan nasional; salah satu pendiri dan ketua pertama Dewan Waligereja (cikal bakal KWI)."
  },
  {
    name: "Lambertus van den Heuvel Sugiri, S.J.", title: "Pater", died: "11 Juni 2020 (usia 89)",
    born: "23 Desember 1930, Belanda",
    entered: "Masuk Serikat Jesus 1951; datang ke Indonesia 1952 (novisiat Girisonta)",
    firstVows: "",
    ordination: "Imam Jesuit",
    vows: "",
    studies: "Filsafat Yogyakarta (1955–1958); TOK Seminari Mertoyudan (1958–1961); teologi; tersiat di Jerman (1966). Pastor di Paroki St. Theresia Jakarta (2005–2020); dikenal sebagai 'bapak' Gerakan Karismatik Katolik Indonesia."
  },
  {
    name: "Yustinus Triyono, S.J.", title: "Bruder", died: "25 Oktober 2021 (usia 55)",
    born: "21 Desember 1965, Ganjuran, Bantul",
    entered: "7 Juli 1987 — Novisiat St. Stanislaus Kostka, Girisonta",
    firstVows: "8 Juli 1989",
    ordination: "Bruder (tidak ditahbiskan)",
    vows: "2 Februari 2016 — Gereja Santo Stanislaus Kostka",
    studies: "Filsafat STF Driyarkara (1989–1993); Magister Manajemen Pendidikan (bimbingan & konseling), De La Salle University, Manila, Filipina (1997–2000)."
  },
];

/* ---------- PROVINSIAL SJ INDONESIA (dari artikel "Provincial dari Masa ke Masa") ---------- */
const provincials = [
  { name: "P. Albertus Bagus Laksana", period: "2026–2032", detail: "Provincial kini; teolog komparatif; mantan Rektor Universitas Sanata Dharma.", photo: "photos/bagus-laksana.png" },
  { name: "P. Benedictus Hari Juliawan", period: "2020–2026", detail: "Pater Benny; dari Ambarawa; doktor Development Studies, Oxford.", photo: "photos/hari-juliawan.jpg" },
  { name: "P. Petrus Sunu Hardiyanta", period: "2014–2020", detail: "Pater Sunu; dari Medari, Yogyakarta; kini instruktur tersiat Girisonta.", photo: "photos/sunu-hardiyanta.jpg" },
  { name: "P. Robertus Bellarminus Rijo Moersanto", period: "2008–2014", detail: "Pater Riyo; dari Magelang; kini superior Misi Pakistan.", photo: "photos/rijo-moersanto.jpg" },
  { name: "P. Agustinus Priyono Marwan", period: "2002–2008", detail: "Pater Pri Marwan; dari Surakarta; latar belakang psikologi.", photo: "photos/priyono-marwan.jpg" },
  { name: "P. Paulus Wiryono Priyotamtama", period: "1996–2002", detail: "Pater Wir; dari Madiun; memimpin masa Reformasi 1998.", photo: "photos/wiryono.jpg" },
  { name: "P. Carolus Putranto", period: "1990–1996", detail: "Dari Sukabumi; menjadi provincial pada usia 39. Teolog dogmatik.", photo: "photos/putranto.jpg" },
  { name: "P. Franciscus Xaverius Danuwinata", period: "1989–1990", detail: "Pater Danu; dari Purwodadi; tokoh pendidikan tinggi. Wafat 26 Agt 2016.", photo: "photos/danuwinata.jpg" },
  { name: "P. Josephus Darminta", period: "1984–1989", detail: "Pater Darminta; dari Kalasan, Yogyakarta; penulis spiritualitas Ignasian.", photo: "photos/darminta.jpg", photoZoom: true },
  { name: "Kardinal Julius Darmaatmadja", period: "1981–1983", detail: "Dari Muntilan; kelak Uskup Agung Semarang & Jakarta, Kardinal 1994.", photo: "photos/darmaatmadja.jpg" },
  { name: "P. Paulus Suradibrata", period: "1975–1981", detail: "Pater Sura; dari Bantul. Orang Asia pertama jadi Asisten Jenderal Asia Timur & Oseania. Wafat 1 Jan 2018.", photo: "photos/suradibrata.jpg" },
  { name: "P. Antonius Soenarja", period: "1971–1975", detail: "Provincial pertama; dari Klaten. Wafat 30 Sep 1988.", photo: "photos/soenarja.jpg" },
];

/* ---------- RINGKASAN PROVINSI & KOMUNITAS ----------
   Sumber: halaman Komunitas jesuits.id (jumlah anggota & superior).
   Daftar anggota per komunitas TIDAK dipublikasikan; nama di bawah disusun
   dari penugasan/role yang tersedia dan bersifat perkiraan (belum lengkap).
   Total resmi Provinsi Indonesia (2021): 339 Jesuit = 246 imam + 74 skolastik + 19 bruder. */
const provinceStats = {
  asOf: "2021", total: 339, priests: 246, scholastics: 74, brothers: 19,
  source: "JCAP / Provinsi Indonesia SJ"
};

const communities = [
  { name: "Kolese St. Robertus Bellarminus", place: "Yogyakarta (Mrican)", superior: "P. Benedictus Hari Juliawan", priests: 22, scholastics: 0, brothers: 3, total: 25, members: ["P. Benedictus Hari Juliawan", "P. Bonaventura Hartaja Toto Budyarja", "P. Stephanus Hari Suparwito"] },
  { name: "Kolese Johanes de Britto", place: "Yogyakarta", superior: "P. Antonius Gustawan", priests: 11, scholastics: 1, brothers: 1, total: 13, members: ["P. Antonius Gustawan", "P. Harry Setianto Sunaryo"] },
  { name: "Komunitas Bener", place: "Bener, Purworejo", superior: "P. Yosephus Ispuroyanto Iswarahadi", total: null, members: ["P. Yosephus Ispuroyanto Iswarahadi"] },
  { name: "Kolese St. Ignatius", place: "Yogyakarta", superior: "P. Andreas Sugijopranoto", priests: 18, scholastics: 16, brothers: 3, total: 37, members: ["P. Andreas Sugijopranoto", "P. Bernadus Dirgaprimawan", "P. Paulus Bambang Irawan", "F. Y Sunari", "S. Septian Kurniawan"] },
  { name: "Santo Stanislaus", place: "Girisonta", superior: "P. Laurentius Priyo Poedjiono", priests: 34, scholastics: 0, brothers: 3, novices: 18, total: 55, members: ["P. Laurentius Priyo Poedjiono", "P. Joannes de Britto Dwijo Atmoko", "P. Yohanes Alis Windu Prasetya", "P. Joannes Abdipranata", "P. Alexander Hendra Dwi Asmara", "Br. Nicolaus David Kristianto"] },
  { name: "Kolese Mikael", place: "Surakarta", superior: "P. Markus Sjamsul Wanandi", priests: 12, scholastics: 1, brothers: 1, total: 14, members: ["S. Roberthus Kalis Jati Irawan", "P. Tiro Angelo Daenuwy"] },
  { name: "Komunitas Santo Yusup", place: "Indonesia", superior: "", priests: 13, scholastics: 0, brothers: 0, total: 13, members: ["P. Rafael Mathando Hinganaday", "P. Benedictus Cahyo Christanto"] },
  { name: "Rumah Provinsialat SJ", place: "Semarang", superior: "P. Bambang Alfred Sipayung", priests: 13, scholastics: 0, brothers: 2, total: 15, members: ["P. Bambang Alfred Sipayung", "P. Herman Joseph Suhardiyanto", "P. Antonius Septian Marhenanto", "P. Robertus Sigit Adi Nugroho"] },
  { name: "Kolese Loyola", place: "Indonesia", superior: "", priests: 5, scholastics: 2, brothers: 0, total: 7, members: [] },
  { name: "Kolese Le Cocq d'Armandville", place: "Papua", superior: "P. Yohanes Sudriyanto", priests: 7, scholastics: 0, brothers: 2, total: 9, members: ["P. Yohanes Sudriyanto"] },
  { name: "Seminari St. Petrus Kanisius", place: "Mertoyudan", superior: "P. Leo Agung Sardi", priests: 9, scholastics: 1, brothers: 1, total: 11, members: ["P. Leo Agung Sardi", "P. Gregorius Agung Satriyo Wibisono", "S. Beda Holy Septianno", "P. Joannes Maryana"] },
  { name: "Kolese St. Petrus Kanisius", place: "Wonosari", superior: "P. Joannes Heru Hendarto", priests: 10, scholastics: 2, brothers: 3, total: 15, members: ["P. Joannes Heru Hendarto"] },
  { name: "Beato Rupert Mayer", place: "Jakarta", superior: "", priests: 18, scholastics: 0, brothers: 0, total: 18, members: ["P. Macarius Maharsono Probho", "P. Yohanes Deodatus", "P. Bernardus Christian Triyudo Prastowo"] },
  { name: "Beato Miguel Pro", place: "Jakarta", superior: "P. Simon Petrus Bambang Ponco Santosa", total: null, members: ["P. Simon Petrus Bambang Ponco Santosa", "P. Ignatius Suryadi"] },
  { name: "Kolese Hermanum", place: "Jakarta", superior: "", total: null, members: ["P. Thomas Hidya Tjaya", "P. Ferdinandus Effendi Kusuma Sunur", "P. Thomas Aquinas Maswan Susinto", "P. Josephus Ageng Marwata", "P. Odemus Bei Witono", "P. Ignatius Windar Santoso", "S. Adrianus Raditya Indriyatno"] },
  { name: "Komunitas Gonzaga", place: "Jakarta", superior: "P. Emmanuel Baskoro Poedjinoegroho", total: null, members: ["P. Emmanuel Baskoro Poedjinoegroho", "P. Eduard C. Ratu Dopo", "P. Yulius Suroso"] },
  { name: "Kolese Kanisius", place: "Menteng, Jakarta", superior: "P. Leonardus Evert Bambang Winandoko", total: null, members: ["P. Leonardus Evert Bambang Winandoko", "P. Benedictus Bambang Triatmoko", "P. Thomas Becket Gandi Hartana", "P. Markus Sjamsul Wanandi", "P. Alexander Koko Siswijayanto", "P. Albertus Buddy Haryadi", "P. Baskara T. Wardaya", "P. Ignatius Ismartono", "P. Christoforus Kristiono Puspo", "P. Heinrich Angga Indraswara", "Br. Matheus Sugiyono", "Fr. Leander Emanuel Arya Wikan Prabantara"] },
  { name: "Komunitas ATMI Cikarang", place: "Cikarang", superior: "", total: null, members: ["P. Yakobus Rudiyanto", "P. Tiburtius Agus Sriyono"] },
];

/* Anggota yang komunitasnya belum teridentifikasi dari data publik. */
const otherJesuits = [
  { name: "P. Vincentius Doni Erlangga Satriawan", role: "Koordinator Tim Promosi Panggilan" },
  { name: "P. Paulus Agung Wijayanto", role: "Pastor Kepala Gereja Paroki Internasional St. Petrus Canisius" },
  { name: "P. Heribertus Heri Setyawan", role: "Studi khusus magister ilmu sejarah, SOAS - University of London" },
  { name: "P. Ernest Justin", role: "Studi magister psikologi terapan, Universitas Fordham" },
  { name: "P. Romanus Wahana Wegig", role: "Vikaris Parokial Paroki Santo Yusup" },
  { name: "P. Martinus Dam Febrianto", role: "Direktur JRS Indonesia" },
  { name: "P. Filipus Frederick Ray Popo", role: "Studi khusus filsafat, Brown University" },
  { name: "P. Philipus Bagus Widyawan", role: "Pastor Kepala Paroki Santo Yohanes Pemandi" },
  { name: "P. Peter Benedicto Devantara", role: "Pastor Rekan Paroki Santo Petrus dan Paulus" },
  { name: "P. Andreas Agung Nugroho", role: "Pastor Rekan Paroki Santa Maria Diangkat ke Surga (Katedral)" },
  { name: "P. Amadea Prajna Putra Mahardika", role: "Studi teologi sistematik, Jesuit School of Theology, Santa Clara University" },
  { name: "P. Klaus Heinrich Raditio", role: "Pastor Rekan Gereja Paroki Internasional St. Petrus Canisius & staf STF Driyarkara" },
  { name: "P. Simon Arief Herdian Putra Tama", role: "Staf KPTT" },
  { name: "S. Yohanes Ignasius Setiawan", role: "Studi psikologi, Universitas Gregoriana" },
  { name: "S. Arnoldus Iga Pradipta", role: "Formasi filsafat, STF Driyarkara" },
  { name: "S. John Fisher Gading Winugraha", role: "Formasi filsafat, STF Driyarkara" },
  { name: "S. Efrem Mas Aletadeo Satya Pramuda", role: "Formasi filsafat, STF Driyarkara" },
  { name: "S. Realino Halford Triatmaja", role: "Formasi filsafat, STF Driyarkara" },
  { name: "S. Karel Amadeus Effendi", role: "Formasi filsafat, STF Driyarkara" },
  { name: "S. Antonius Vinsensius Egwin Gawe", role: "Formasi filsafat, STF Driyarkara" },
  { name: "P. Laurentius Sutarno", role: "Pastor Rekan Gereja Paroki Santo Servatius" },
  { name: "P. Christoporus Aria Prabantara", role: "Pastor Rekan Gereja Santa Theresia" },
  { name: "P. Adrianus Suyadi", role: "Anggota Konsultor Serikat Jesus Provinsi Indonesia" },
  { name: "P. Cyprianus Kuntoro Adi", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026" },
  { name: "P. Dominico Savio Octariano Widiantoro", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026" },
  { name: "P. Melkyor Pando", role: "Anggota Coetus Praevius Kongregasi Provinsi 2026" },
  { name: "S. Feliks Erasmus Arga", role: "Formasi Tahap Orientasi Kerasulan (TOK), Xavier High School" },
  { name: "S. Sirilus Hari Prasetyo", role: "Formasi TOK, SMK PIKA" },
  { name: "S. Yohanes Deo Yudistiro Utomo", role: "Formasi TOK, SMA Adhi Luhur" },
  { name: "S. Alfonsus Ignatius Franky Njoto", role: "Formasi Teologi, Loyola School of Theology, Ateneo de Manila University" },
  { name: "S. Engelbertus Viktor Daki", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)" },
  { name: "S. Klemens Yuris Widya Denanta", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)" },
  { name: "S. Teilhard Aurobindo Soesilo", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)" },
  { name: "S. Mikael Tri Karitasanto", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)" },
  { name: "S. Leonardo Ardhani Escriva Pamungkas", role: "Formasi Teologi, Fakultas Teologi Wedabhakti (FTW)" },
  { name: "P. Hugo Bayu Hadibowo", role: "Pastor Rekan Paroki Santa Maria Bunda Allah" },
  { name: "P. Martinus Juprianto Bulu Toding", role: "Pendamping mahasiswa Universitas Sanata Dharma" },
  { name: "P. Franciscus Xaverius Murti Hadi Wijayanto", role: "Co-delegatus Ongoing Formation" },
  { name: "P. Agustinus Sarwanto", role: "Komisi Keuangan Provindo" },
  { name: "P. Albertus Sadhyoko Rahardjo", role: "Komisi Keuangan Provindo" },
  { name: "P. Yusup Edi Mulyono", role: "Komisi Keuangan Provindo" },
  { name: "P. Athanasius Kristiono Purwadi", role: "Pastor Kepala Paroki Hati Santa Perawan Maria Tak Bernoda" },
  { name: "P. Franciscus Xaverius Dedomau Djatmiko da Gomez", role: "Pastor Kepala Paroki Santa Perawan Maria Ratu" },
  { name: "P. Antonius Dhimas Hardjuna", role: "Pastor Kepala Gereja Paroki Santa Maria Bunda Allah" },
  { name: "P. Ignatius Swasono", role: "Staf Campus Ministry Universitas Sanata Dharma" },
  { name: "P. Justinus Sigit Prasadja", role: "Pastor Rekan Paroki Santo Robertus Bellarminus" },
  { name: "P. Paulus Andri Astanto", role: "Pastor Kepala Gereja Paroki Santo Robertus Bellarminus" },
  { name: "P. Yohanes Harry Kristanto", role: "Persiapan penugasan Misi Pakistan" },
  { name: "P. Emanuel Baskoro Poedjinoegroho", role: "Panitia Pembangunan Kolese Xaverius" },
  { name: "P. Joannes Moerti Yoedho Koesoemo", role: "Panitia Pembangunan Kolese Xaverius" },
  { name: "P. Johannes Adrianus Hendra Sutedja", role: "Panitia Pembangunan Kolese Xaverius" },
  { name: "P. Julius Mario Plea Lagaor", role: "Panitia Pembangunan Kolese Xaverius" },
  { name: "P. Mario Tomi Subardjo", role: "Pengajar Loyola School of Theology" },
  { name: "P. Fransiskus Pieter Dolle", role: "Tim Promosi Panggilan" },
  { name: "P. Hendricus Satya Wening Pambudi", role: "Tim Promosi Panggilan" },
  { name: "P. Paulus Hastra Kurdani", role: "Tim Promosi Panggilan" },
  { name: "F. Franciscus Xaverius Marsono", role: "Tim Promosi Panggilan untuk Bruder" },
  { name: "F. Ignatius Ulrig Jumeno", role: "Tim Promosi Panggilan untuk Bruder" },
  { name: "P. Gregorius Soetomo", role: "Moderator Pemuda Katolik Komisariat Daerah DKI Jakarta" },
  { name: "P. Petrus Sunu Hardiyanta", role: "Ketua Pengurus Yayasan Taman Tani" },
  { name: "P. Synesius Suyitna", role: "Sekretaris Pengurus Yayasan Taman Tani" },
  { name: "P. Andreas Aryono Mantiri", role: "Bendahara Pengurus Yayasan Taman Tani / Asisten Ekonom Provindo" },
  { name: "P. Stefanus Hendrianto", role: "Imam Jesuit Provinsi Jesuits West (Amerika Serikat); ditahbiskan 8 Juni 2019, Gereja Our Lady of La Vang, Portland, Oregon; mantan aktivis pro-demokrasi 1998" },
  { name: "P. Agustinus Winaryanta", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Christoforus Bayu Risanto", role: "Ahli Meteorologi, Vatican Observatory & Research Associate, University of Arizona" },
  { name: "P. Thomas Septi Widhiyudana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Nicolaus Devianto Fajar Trinugroho", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Stephanus Advent Novianto", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Aluisius Pramudya Daniswara", role: "Pastor Paroki Blok B, Keuskupan Agung Jakarta" },
  { name: "P. Rikhardus Sani Wibowo", role: "Presenter, Ignatian Leadership Program, SMA Adhi Luhur" },
  { name: "P. Joseph Mangatur Mangisi Tua Situmorang", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Eduardus Didik Chahyono Widyatama", role: "Pastor Paroki St. Theresia" },
  { name: "P. Yulius Eko Sulistyo", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Antonius Sumarwan", role: "Koordinator Nasional Jaringan Doa Bapa Suci Sedunia (PWPN) Indonesia" },
  { name: "P. Aluisius Dian Permana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Alfonsus Ardi Jatmiko", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Evodius Sapto Jati Nugroho", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Antonius Bagas Prasetya", role: "Vikaris Parokial, Paroki Santo Antonius Padua" },
  { name: "P. Isodorus Bangkit Susetyo Adi Nugroho", role: "Staf SMA YPPK Adhi Luhur" },
  { name: "P. Leo Perkasa Tanjung", role: "Studi Kitab Suci di Biblicum" },
  { name: "P. Jacobus Aditya Christie Manggala", role: "Direktur Campus Ministry, Universitas Sanata Dharma" },
  { name: "P. Roberthus (Robert) Rimmin", role: "Imam Jesuit senior; karya misi di Timor Leste sejak tahbisan" },
  { name: "Br. Yohanes Sarju", role: "Kepala Departemen Pengembangan SDM – Pelayanan Umum – Tenaga Gereja, KWI" },
  { name: "P. Fransiskus Wawan Setyadi", role: "Dosen filsafat & Wakil Ketua III STF Driyarkara; pelatih Komisi Komunikasi Sosial (Komsos) KWI" },
  { name: "P. Franz Magnis-Suseno", role: "Dosen Program Doktor Filsafat, STF Driyarkara" },
  { name: "P. Justinus Sudarminta", role: "Ketua Senat Dosen & pengajar S2/S3, STF Driyarkara" },
  { name: "P. Johanes Haryatmoko", role: "Dosen/peneliti (STF Driyarkara / Universitas Sanata Dharma)" },
  { name: "P. Gabriel Possenti Sindhunata", role: "Penulis; redaksi majalah Basis; dosen filsafat" },
  { name: "P. A. Setyo Wibowo", role: "Dosen filsafat, STF Driyarkara" },
  { name: "Kardinal Ignatius Suharyo", role: "Uskup Agung Jakarta (Kardinal, S.J.)" },
  { name: "P. Bernardus Agus Rukiyanto", role: "Wakil Lembaga Kateketik (Perdikkati), Komisi Kateketik KWI" },
  { name: "P. Antonius Vico Christiawan", role: "Sekretaris Komisi Pendidikan KWI" },
  { name: "P. Antonius Dieng Karnedi", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Ignatius Dio Ernanda Johandika", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Leslie Joseph Bingkasan", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Danang Bramasti", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Christoforus Iuliano Mesaroga", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Ignatius Damar Adi Wicaksana", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Agustinus Rudy Chandra Wijaya", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Ignatius Suryadi Prajitno", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Ignatius Drajat Soesilo", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "P. Yohanes Paulus Sunari", role: "Anggota Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "S. Laurensius Herdian Pambudi", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "S. Lambertus Alfred", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "S. Daud Kefas Raditya", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "S. Arnold Lintang Yanviero", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan" },
  { name: "S. Wahyu Mega", role: "Skolastik Serikat Jesus; penugasan terbaru belum dipublikasikan" },
];
